export const CONTEXTUAL_MENU_WIDTH = 400;
export const SCROLL_BAR_WIDTH = 18;

// menu
export const MENU_WIDTH = 45;

// zoom
export const MAX_ZOOM = 32;
export const MIN_ZOOM = 0.1;

// arrowhead
export const ARROWHEAD_STROKE_WIDTH = 5;

// export const TRIANGLE_POINTS = [215, 55, 275, 75, 215, 95];
// export const BARBED_POINTS = TRIANGLE_POINTS.concat([235, 75]);
// export const ELLIPSE_POINTS = [260, 75, 15, 15]; // cx, cy, rx, ry
// export const RECTANGLE_POINTS = [245, 60, 30, 30]; // x, y, width, height
// export const POLYLINE_POINTS = TRIANGLE_POINTS;
//
// export const TRIANGLE_HEIGHT = TRIANGLE_POINTS[5] - TRIANGLE_POINTS[1];
// export const TRIANGLE_LENGTH = TRIANGLE_POINTS[2] - TRIANGLE_POINTS[0];
// export const BARBED_HEIGHT = BARBED_POINTS[5] - BARBED_POINTS[1];
// export const BARBED_LENGTH = BARBED_POINTS[2] - BARBED_POINTS[6];
// export const ELLIPSE_RX = ELLIPSE_POINTS[2];
// export const ELLIPSE_RY = ELLIPSE_POINTS[3];
// export const RECTANGLE_HEIGHT = RECTANGLE_POINTS[2];
// export const RECTANGLE_LENGTH = RECTANGLE_POINTS[3];
// export const POLYLINE_HEIGHT = POLYLINE_POINTS[5] - POLYLINE_POINTS[1];
// export const POLYLINE_LENGTH = POLYLINE_POINTS[2] - POLYLINE_POINTS[0];

export const ARROWHEAD_GUI_WIDTH = 300;
export const ARROWHEAD_GUI_HEIGHT = 150;
export const ARROWHEAD_GUI_BUFFER = 25;

export const TRIANGLE_HEIGHT = 40;
export const TRIANGLE_LENGTH = 60;
export const BARBED_HEIGHT = 40;
export const BARBED_LENGTH = 60;
export const ELLIPSE_RX = 15;
export const ELLIPSE_RY = 15;
export const RECTANGLE_HEIGHT = 30;
export const RECTANGLE_LENGTH = 30;
export const POLYLINE_HEIGHT = 40;
export const POLYLINE_LENGTH = 60;

export const TRIANGLE_POINTS = [
    ARROWHEAD_GUI_WIDTH - ARROWHEAD_GUI_BUFFER - TRIANGLE_LENGTH,
    (ARROWHEAD_GUI_HEIGHT - TRIANGLE_HEIGHT) / 2,
    ARROWHEAD_GUI_WIDTH - ARROWHEAD_GUI_BUFFER,
    ARROWHEAD_GUI_HEIGHT / 2,
    ARROWHEAD_GUI_WIDTH - ARROWHEAD_GUI_BUFFER - TRIANGLE_LENGTH,
    (ARROWHEAD_GUI_HEIGHT + TRIANGLE_HEIGHT) / 2
];
export const BARBED_POINTS = [
    ARROWHEAD_GUI_WIDTH - ARROWHEAD_GUI_BUFFER - (1.25 * BARBED_LENGTH),
    (ARROWHEAD_GUI_HEIGHT - BARBED_HEIGHT) / 2,
    ARROWHEAD_GUI_WIDTH - ARROWHEAD_GUI_BUFFER,
    ARROWHEAD_GUI_HEIGHT / 2,
    ARROWHEAD_GUI_WIDTH - ARROWHEAD_GUI_BUFFER - (1.25 * BARBED_LENGTH),
    (ARROWHEAD_GUI_HEIGHT + BARBED_HEIGHT) / 2,
    ARROWHEAD_GUI_WIDTH - ARROWHEAD_GUI_BUFFER - BARBED_LENGTH,
    ARROWHEAD_GUI_HEIGHT / 2
];
export const ELLIPSE_POINTS = [
    ARROWHEAD_GUI_WIDTH - ARROWHEAD_GUI_BUFFER - ELLIPSE_RX,
    ARROWHEAD_GUI_HEIGHT / 2,
    ELLIPSE_RX,
    ELLIPSE_RY
];
export const RECTANGLE_POINTS = [
    ARROWHEAD_GUI_WIDTH - ARROWHEAD_GUI_BUFFER - RECTANGLE_LENGTH,
    (ARROWHEAD_GUI_HEIGHT - RECTANGLE_HEIGHT) / 2,
    RECTANGLE_LENGTH,
    RECTANGLE_HEIGHT
];
export const POLYLINE_POINTS = TRIANGLE_POINTS;
